final SERVANT_OPTIONS = [
  '1 - Mash Kyrielight',
  '2 - Altria Pendragon',
  '3 - Altria Pendragon (Alter)',
  '4 - Altria Pendragon (Lily)',
  '5 - Nero Claudius',
  '6 - Siegfried',
  '7 - Gaius Julius Caesar',
  '8 - Altera',
  '9 - Gilles de Rais',
  '10 - Chevalier d\'Eon',
  '11 - EMIYA',
  '12 - Gilgamesh',
  '13 - Robin Hood',
  '14 - Atalante',
  '15 - Euryale',
  '16 - Arash',
  '17 - Cu Chulainn',
  '18 - Elisabeth Bathory',
  '19 - Musashibou Benkei',
  '20 - Cu Chulainn (Prototype)',
  '21 - Leonidas',
  '22 - Romulus',
  '23 - Medusa',
  '24 - Georgios',
  '25 - Edward Teach',
  '26 - Boudica',
  '27 - Ushiwakamaru',
  '28 - Alexander',
  '29 - Marie Antoinette',
  '30 - Saint Martha',
  '31 - Medea',
  '32 - Gilles de Rais (Caster)',
  '33 - Hans Christian Andersen',
  '34 - William Shakespeare',
  '35 - Mephistopheles',
  '36 - Wolfgang Amadeus Mozart',
  '37 - Zhuge Liang (El-Melloi II)',
  '38 - Cu Chulainn (Caster)',
  '39 - Sasaki Kojiro',
  '40 - Hassan of the Cursed Arm',
  '41 - Stheno',
  '42 - Jing Ke',
  '43 - Charles-Henri Sanson',
  '44 - Phantom of the Opera',
  '45 - Mata Hari',
  '46 - Carmilla',
  '47 - Heracles',
  '48 - Lancelot',
  '49 - Lu Bu Fengxian',
  '50 - Spartacus',
  '51 - Sakata Kintoki',
  '52 - Vlad III',
  '53 - Asterios',
  '54 - Caligula',
  '55 - Darius III',
  '56 - Kiyohime',
  '57 - Eric Bloodaxe',
  '58 - Tamamo Cat',
  '59 - Jeanne d\'Arc',
  '60 - Orion',
  '61 - Elisabeth Bathory (Halloween)',
  '62 - Tamamo no Mae',
  '63 - David',
  '64 - Hektor',
  '65 - Francis Drake',
  '66 - Anne Bonny & Mary Read',
  '67 - Medea (Lily)',
  '68 - Okita Souji',
  '69 - Oda Nobunaga',
  '70 - Scathach',
  '71 - Diarmuid ua Duibhne',
  '72 - Fergus mac Roich',
  '73 - Altria Pendragon (Santa Alter)',
  '74 - Nursery Rhyme',
  '75 - Jack the Ripper',
  '76 - Mordred',
  '77 - Nikola Tesla',
  '78 - Altria Pendragon (Lancer Alter)',
  '79 - Paracelsus von Hohenheim',
  '80 - Charles Babbage',
  '81 - Henry Jekyll & Hyde',
  '82 - Frankenstein',
  '83 - Solomon (Grand Caster)',
  '84 - Arjuna',
  '85 - Karna',
  '86 - Mysterious Heroine X',
  '87 - Fionn mac Cumhaill',
  '88 - Brynhild',
  '89 - Beowulf',
  '90 - Nero Claudius (Bride)',
  '91 - Ryougi Shiki (Saber)',
  '92 - Ryougi Shiki (Assassin)',
  '93 - Amakusa Shirou',
  '94 - Astolfo',
  '95 - Kid Gilgamesh',
  '96 - Edmond Dantes',
  '97 - Nightingale',
  '98 - Cu Chulainn (Alter)',
  '99 - Queen Medb',
  '100 - Helena Blavatsky',
  '101 - Rama',
  '102 - Li Shuwen',
  '103 - Thomas Edison',
  '104 - Geronimo',
  '105 - Billy the Kid',
  '106 - Jeanne d\'Arc (Alter)',
  '107 - Angra Mainyu',
  '108 - Iskandar',
  '109 - EMIYA (Assassin)',
  '110 - Hassan of the Hundred Personas',
  '111 - Irisviel (Dress of Heaven)',
  '112 - Shuten-Douji',
  '113 - Xuanzang Sanzang',
  '114 - Minamoto-no-Raikou',
  '115 - Sakata Kintoki (Rider)',
  '116 - Ibaraki-Douji',
  '117 - Fuuma Kotarou',
  '118 - Ozymandias',
  '119 - Altria Pendragon (Lancer)',
  '120 - Nitocris',
  '121 - Lancelot (Saber)',
  '122 - Tristan',
  '123 - Gawain',
  '124 - Hassan of the Serenity',
  '125 - Tawara Touta',
  '126 - Bedivere',
  '127 - Leonardo da Vinci',
  '128 - Tamamo no Mae (Lancer)',
  '129 - Altria Pendragon (Archer)',
  '130 - Marie Antoinette (Caster)',
  '131 - Anne Bonny & Mary Read (Archer)',
  '132 - Mordred (Rider)',
  '133 - Scathach (Assassin)',
  '134 - Kiyohime (Lancer)',
  '135 - Saint Martha (Ruler)',
  '136 - Illyasviel von Einzbern',
  '137 - Chloe von Einzbern',
  '138 - Elisabeth Bathory (Brave)',
  '139 - Cleopatra',
  '140 - Vlad III (EXTRA)',
  '141 - Jeanne d\'Arc (Santa Lily Alter)',
  '142 - Ishtar',
  '143 - Enkidu',
  '144 - Quetzalcoatl',
  '145 - Gilgamesh (Caster)',
  '146 - Medusa (Lancer)',
  '147 - Gorgon',
  '148 - Jaguar Man',
  '149 - Tiamat',
  '150 - Merlin',
  '151 - Goetia',
  '153 - Miyamoto Musashi',
  '154 - King Hassan',
  '155 - Mysterious Heroine X (Alter)',
  '156 - Shinjuku (Archer)',
  '157 - EMIYA (Alter)',
  '158 - Avenger of Shinjuku',
  '159 - Assassin of Shinjuku',
  '160 - Arthur Pendragon (Prototype)',
  '161 - Hijikata Toshizo',
  '162 - Chacha',
  '163 - Meltryllis',
  '164 - Passionlip',
  '165 - Suzuka Gozen',
  '166 - BB',
  '167 - Sessyoin Kiara',
  '168 - Beast III/R',
  '169 - Caster of the Nightless City',
  '170 - Wu Zetian',
  '171 - Penthesilea',
  '172 - Christopher Columbus',
  '173 - Sherlock Holmes',
  '174 - Paul Bunyan',
  '175 - Nero Claudius (Caster)',
  '176 - Frankenstein (Saber)',
  '177 - Nitocris (Assassin)',
  '178 - Oda Nobunaga (Berserker)',
  '179 - Altria Pendragon (Rider Alter)',
  '180 - Helena Blavatsky (Archer)',
  '181 - Minamoto no Raikou (Lancer)',
  '182 - Ishtar (Rider)',
  '183 - Parvati',
  '184 - Tomoe Gozen',
  '185 - Mochizuki Chiyome',
  '186 - Houzouin Inshun',
  '187 - Munenori Yagyu',
  '188 - Katou Danzou',
  '189 - Osakabehime',
  '190 - Mecha Eli-chan',
  '191 - Mecha Eli-chan Mk.II',
  '192 - Okeanos Caster',
  '193 - Nezha',
  '194 - Midrash Caster',
  '195 - Abigail Williams',
  '196 - Ereshkigal',
  '197 - Altera the San(ta)',
  '198 - Katsushika Hokusai',
  '199 - Semiramis',
  '200 - Asagami Fujino',
  '201 - Anastasia Nikolaevna Romanova',
  '202 - Atalante (Alter)',
  '203 - Avicebron',
  '204 - Antonio Salieri',
  '205 - Ivan the Terrible',
  '206 - Achilles',
  '207 - Chiron',
  '208 - Sieg',
  '209 - Okita Souji (Alter)',
  '210 - Okada Izou',
  '211 - Sakamoto Ryouma',
];